### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by gavinlaking** [tristil/minder#2]
Hi,

Having cloned/forked the repository for local development, I'm trying to run the test suite for the first time. There isn't a Rake task for this, so I resorted to `bundle exec rspec spec`. However, this also fails for me with the following (truncated) stack trace:

```
Gemfile Found, running with bundle exec
/home/gavinlaking/.gem/ruby/2.2.2/gems/virtus-1.0.5/lib/virtus/const_missing_extensions.rb:14:in `const_missing': uninitialized constant Minder::WorkPeriod::DEFAULT_WORK_PERIOD (NameError)
    from /home/gavinlaking/Source/minder/lib/minder/pomodoro/work_period.rb:5:in `<class:WorkPeriod>'
    from /home/gavinlaking/Source/minder/lib/minder/pomodoro/work_period.rb:4:in `<module:Minder>'
    from /home/gavinlaking/Source/minder/lib/minder/pomodoro/work_period.rb:3:in `<top (required)>'
    from /home/gavinlaking/Source/minder/lib/minder/pomodoro/pomodoro_runner.rb:3:in `require'
    from /home/gavinlaking/Source/minder/lib/minder/pomodoro/pomodoro_runner.rb:3:in `<top (required)>'
    from /home/gavinlaking/Source/minder/lib/minder/application.rb:2:in `require'
    from /home/gavinlaking/Source/minder/lib/minder/application.rb:2:in `<top (required)>'
    from /home/gavinlaking/Source/minder/spec/minder/application_spec.rb:1:in `require'
    from /home/gavinlaking/Source/minder/spec/minder/application_spec.rb:1:in `<top (required)>'
    from /home/gavinlaking/.gem/ruby/2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
```

Please could you let me know how to run the tests :-)

Gav

**Comment by tristil** [comment]
Test suite is broken atm. It's just been one loooong spike for a long time. That's why I wanted to get end-to-end tests working as coverage while I got back to sanity with the unit tests. I'll get them passing again soon, I promise.

**Comment by gavinlaking** [comment]
(Shame on you! ;-) ) No worries, I'll have a hack about and see if I can do some work on the `migrate_to_vedeu` branch, I'll try not to break too much!

**Comment by tristil** [comment]
Awesome, thanks!
